# Generated by Django 5.2.3 on 2025-06-29 07:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('date_inscri', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('date_inscri', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointRecup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Repas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('est_dispo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('geo_position', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatutCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StatutLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StatutLivreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StatutRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StatutZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeRepas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='core.client')),
                ('point_recup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pointrecup')),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribue_le', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='core.commande')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='core.livreur')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage_reduction', models.PositiveIntegerField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('repas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='core.repas')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueStatutCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mis_a_jour_le', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='core.commande')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.statutcommande')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueStatutLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mis_a_jour_le', models.DateTimeField(auto_now_add=True)),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='core.livraison')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.statutlivraison')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueStatutLivreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mis_a_jour_le', models.DateTimeField(auto_now_add=True)),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='core.livreur')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.statutlivreur')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueStatutRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mis_a_jour_le', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='core.restaurant')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.statutrestaurant')),
            ],
        ),
        migrations.AddField(
            model_name='repas',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.typerepas'),
        ),
        migrations.CreateModel(
            name='HistoriqueStatutZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mis_a_jour_le', models.DateTimeField(auto_now_add=True)),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.statutzone')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='core.zone')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeRepas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.PositiveIntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repas_commandes', to='core.commande')),
                ('repas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_repas', to='core.repas')),
            ],
            options={
                'unique_together': {('commande', 'repas')},
            },
        ),
        migrations.CreateModel(
            name='RestaurantRepas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.BooleanField(default=True)),
                ('repas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants_repas', to='core.repas')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repas_restaurants', to='core.restaurant')),
            ],
            options={
                'unique_together': {('restaurant', 'repas')},
            },
        ),
        migrations.CreateModel(
            name='ZoneRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones_restaurants', to='core.restaurant')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants_zones', to='core.zone')),
            ],
            options={
                'unique_together': {('zone', 'restaurant')},
            },
        ),
    ]
