# Generated by Django 5.2.3 on 2025-07-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='mot_de_passe',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
