# Generated by Django 5.2.3 on 2025-06-30 17:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteCommandesJournalieres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_commandes', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='date_debut',
            new_name='date_concerne',
        ),
        migrations.AlterUniqueTogether(
            name='zonerestaurant',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='commanderepas',
            name='prix_unitaire',
        ),
        migrations.RemoveField(
            model_name='pointrecup',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='repas',
            name='est_dispo',
        ),
        migrations.RemoveField(
            model_name='restaurantrepas',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='statutcommande',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='statutlivraison',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='statutlivreur',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='statutrestaurant',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='statutzone',
            name='nom',
        ),
        migrations.AddField(
            model_name='commanderepas',
            name='ajoute_le',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pointrecup',
            name='geo_position',
            field=models.CharField(blank=True, default='0,0', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statutcommande',
            name='appellation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statutlivraison',
            name='appellation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statutlivreur',
            name='appellation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statutrestaurant',
            name='appellation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statutzone',
            name='appellation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_inscri',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='cree_le',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='commanderepas',
            name='quantite',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='historiquestatutcommande',
            name='mis_a_jour_le',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historiquestatutlivraison',
            name='mis_a_jour_le',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historiquestatutlivreur',
            name='mis_a_jour_le',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historiquestatutrestaurant',
            name='mis_a_jour_le',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historiquestatutzone',
            name='mis_a_jour_le',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='attribue_le',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='livreur',
            name='contact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livreur',
            name='date_inscri',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pointrecup',
            name='nom',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='pourcentage_reduction',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='repas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.repas'),
        ),
        migrations.AlterField(
            model_name='repas',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repas',
            name='prix',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='geo_position',
            field=models.CharField(blank=True, default='0,0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantrepas',
            name='repas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.repas'),
        ),
        migrations.AlterField(
            model_name='restaurantrepas',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant'),
        ),
        migrations.AlterField(
            model_name='typerepas',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='zone',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='zonerestaurant',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant'),
        ),
        migrations.AlterField(
            model_name='zonerestaurant',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zone'),
        ),
        migrations.AlterUniqueTogether(
            name='zonerestaurant',
            unique_together={('restaurant', 'zone')},
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.IntegerField()),
                ('mis_a_jour_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('le_jour', models.IntegerField()),
                ('horaire_debut', models.TimeField()),
                ('horaire_fin', models.TimeField()),
                ('mis_a_jour_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='HoraireSpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_concerne', models.DateField()),
                ('horaire_debut', models.TimeField()),
                ('horaire_fin', models.TimeField()),
                ('mis_a_jour_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant')),
            ],
        ),
    ]
