# Generated by Django 5.2.3 on 2025-06-30 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_limitecommandesjournalieres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaire',
            name='mis_a_jour_le',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaire', to='core.restaurant'),
        ),
    ]
