# Generated by Django 5.2.3 on 2025-07-09 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_commande_point_recup'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='suiviscommande',
            unique_together={('commande', 'restaurant')},
        ),
    ]
