# Generated by Django 5.2.3 on 2025-07-06 13:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_restaurant_mot_de_passe'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuivisCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.BooleanField(default=False)),
                ('mis_a_jour_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_commandes', to='core.commande')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_commandes', to='core.restaurant')),
            ],
            options={
                'ordering': ['-mis_a_jour_le'],
                'unique_together': {('commande', 'restaurant', 'mis_a_jour_le')},
            },
        ),
    ]
