# Generated by Django 5.2.3 on 2025-07-06 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_suiviscommande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('date_inscri', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
