# Generated by Django 5.2.3 on 2025-07-02 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_horaire_mis_a_jour_le_alter_horaire_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneLivreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.livreur')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zone')),
            ],
            options={
                'unique_together': {('zone', 'livreur')},
            },
        ),
    ]
