# Generated by Django 5.2.3 on 2025-07-03 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_modepaiement_commande_mode_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibiliteRepas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_dispo', models.BooleanField(default=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('repas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='core.repas')),
            ],
        ),
    ]
